name:                pogo
version:             0.1.0.0
github:              "githubuser/pogo"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/pogo#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - containers
  - arithmoi
  - lens
  - generic-deriving
  ghc-options:
  - -fno-warn-partial-type-signatures
  default-extensions:
  - MonadComprehensions
  - LambdaCase
  - MultiWayIf
  - ViewPatterns
  - MultiParamTypeClasses
  - FunctionalDependencies
  - TypeFamilies
  - TupleSections
  - ScopedTypeVariables
  - RecursiveDo
  - StandaloneDeriving
  - EmptyCase
  - DoAndIfThenElse
  - NondecreasingIndentation
  - ApplicativeDo
  - ConstrainedClassMethods
  - NamedFieldPuns
  - RecordWildCards
  - ParallelListComp
  - PartialTypeSignatures
  - TransformListComp

executables:
  test:
    source-dirs: test
    main: Main.hs
    dependencies:
    - base
    - pogo
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N4
    - -O3
    - -fllvm
